# Generated by Django 4.2.2 on 2023-06-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_alter_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 29, 7, 54, 45, 288148, tzinfo=datetime.timezone.utc)),
        ),
    ]
